/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;
import sqlbackup.SqlBackupRestore;

/**
 *
 * @author ErickaJuliene
 */
public class JFPrincipal extends javax.swing.JFrame {
       JFrame f = new JFrame();
    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jmbPrincipal = new javax.swing.JMenuBar();
        jmCadastros = new javax.swing.JMenu();
        jmiSituacao = new javax.swing.JMenuItem();
        jmiProduto = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiSair = new javax.swing.JMenuItem();
        SQL_backup_ = new javax.swing.JMenu();
        jmRelatorios = new javax.swing.JMenu();
        jmiRelSituacao = new javax.swing.JMenuItem();
        jmiRelProduto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Janela Principal");

        jdpPrincipal.setBackground(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jmCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/12009_16x16.png"))); // NOI18N
        jmCadastros.setText("Cadastros");

        jmiSituacao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiSituacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/12009_16x16.png"))); // NOI18N
        jmiSituacao.setText("Situação");
        jmiSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSituacaoActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiSituacao);

        jmiProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/12015_16x16.png"))); // NOI18N
        jmiProduto.setText("Propriedades");
        jmiProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProdutoActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiProduto);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Proprietários");
        jmCadastros.add(jMenuItem1);
        jmCadastros.add(jSeparator1);

        jmiSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiSair);

        jmbPrincipal.add(jmCadastros);

        SQL_backup_.setText("SQL Backup");
        SQL_backup_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SQL_backup_ActionPerformed(evt);
            }
        });
        jmbPrincipal.add(SQL_backup_);

        jmRelatorios.setText("Relatórios");

        jmiRelSituacao.setText("Situação");
        jmRelatorios.add(jmiRelSituacao);

        jmiRelProduto.setText("Produto");
        jmiRelProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelProdutoActionPerformed(evt);
            }
        });
        jmRelatorios.add(jmiRelProduto);

        jmbPrincipal.add(jmRelatorios);

        setJMenuBar(jmbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProdutoActionPerformed
        JIFPropriedades janela = new JIFPropriedades();
        janela.setVisible(true);
        jdpPrincipal.add(janela);
    }//GEN-LAST:event_jmiProdutoActionPerformed

    private void jmiSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSituacaoActionPerformed
        // TODO add your handling code here:
        //new JFSituacao ().setVisible(true); (alterado)
        JIFSituacao janela = new JIFSituacao ();
        janela.setVisible(true);
        jdpPrincipal.add(janela);
         
    }//GEN-LAST:event_jmiSituacaoActionPerformed

    private void jmiRelProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelProdutoActionPerformed
       JFRelatorio janela = new JFRelatorio();
       janela.showJFRelatorio(this);
    }//GEN-LAST:event_jmiRelProdutoActionPerformed

    private void SQL_backup_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SQL_backup_ActionPerformed
        SqlBackupRestore janela = new SqlBackupRestore();
        janela.setVisible(true);
        jdpPrincipal.add(janela);
    }//GEN-LAST:event_SQL_backup_ActionPerformed

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu SQL_backup_;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenu jmCadastros;
    private javax.swing.JMenu jmRelatorios;
    private javax.swing.JMenuBar jmbPrincipal;
    private javax.swing.JMenuItem jmiProduto;
    private javax.swing.JMenuItem jmiRelProduto;
    private javax.swing.JMenuItem jmiRelSituacao;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiSituacao;
    // End of variables declaration//GEN-END:variables
}
