/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.SituacaoData;
import javax.swing.JOptionPane;
import Model.Produto;
import Model.Situacao;
import Model.Pessoas;
import data.ConexaoMySQL;
import data.ProdutoData;
import data.SituacaoData;
/**
 *
 * @author ErickaJuliene
 */
public class JIFSituacao extends javax.swing.JInternalFrame {

    /**
     * Creates new form JMISituacao
     */
    
    Situacao obj;
    SituacaoData DAO;
    public JIFSituacao() {
        initComponents();
       /* try {
             obj = new Situacao();
             SituacaoData DAO = new SituacaoData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro"+e.getMessage());
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbEditar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jtDescricao = new javax.swing.JTextField();
        jbNovo = new javax.swing.JButton();
        jlId2 = new javax.swing.JLabel();
        jlDescricao = new javax.swing.JLabel();
        jlId = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Situação");
        setEnabled(false);

        jbEditar.setText("Editar");
        jbEditar.setEnabled(false);

        jbCancelar.setText("Cancelar");
        jbCancelar.setEnabled(false);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.setEnabled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.setEnabled(false);

        jbNovo.setText("Novo");
        jbNovo.setEnabled(false);
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jlId2.setText("0");

        jlDescricao.setText("Propriedade");

        jlId.setText("Id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbNovo)
                                .addGap(46, 46, 46)
                                .addComponent(jbSalvar)
                                .addGap(39, 39, 39)
                                .addComponent(jbCancelar))
                            .addComponent(jlDescricao)
                            .addComponent(jlId2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlId)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jbEditar)
                        .addGap(46, 46, 46)
                        .addComponent(jbExcluir)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jlId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlId2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo)
                    .addComponent(jbSalvar)
                    .addComponent(jbCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEditar)
                    .addComponent(jbExcluir))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
    try{ if(validarCampos()){
            if(preencherObjeto()){
                if(true){
                JOptionPane.showMessageDialog(this, 
                        "Salvo com sucesso");
                limparCampos();
                trataCampos(false);
                jbNovo.setEnabled(true);
                jbSalvar.setEnabled(false);
                jbCancelar.setEnabled(false);}
            }
        }
    }catch(Exception erro){
         JOptionPane.showMessageDialog(this, 
                 "Erro ao salvar:"+erro.getMessage(),
                 "Salvar",JOptionPane.ERROR_MESSAGE); }
    }//GEN-LAST:event_jbSalvarActionPerformed

    
    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
       limparCampos();
       tratarCampos(true);
       jbNovo.setEnabled(false);
       jbSalvar.setEnabled(true);
       jbCancelar.setEnabled(true);
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
       limparCampos();
       tratarCampos(false);
       jbNovo.setEnabled(true);
       jbSalvar.setEnabled(false);
       jbCancelar.setEnabled(false);
    }//GEN-LAST:event_jbCancelarActionPerformed
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlDescricao;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlId2;
    private javax.swing.JTextField jtDescricao;
    // End of variables declaration//GEN-END:variables

public void limparCampos(){
    jlId2.setText("O");
    jtDescricao.setText(null);
}
public void tratarcampos(boolean b){ 
    jtDescricao.setEnabled(b);
}
public boolean validarcampos () throws Exception {
    if(jtDescricao.getText().length()<2){
        throw new Exception ("Descrição Inválida");
    }
        return true;
}
    public boolean preencherObjeto () throws Exception {
        obj.setID(Integer.parseInt(jlId2.getText()));
        obj.setDescricao(jtDescricao.getText());
        return true;
    }

    private boolean validarCampos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void trataCampos(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void tratarCampos(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
}